name: Deploy with Capistrano

on:
  push:
    branches:
    - capistrano_deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Restore Bundler cache
      id: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-
    - uses: miloserdow/capistrano-deploy@v2.1
      with:
        target: staging
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
