name: Deploy with Capistrano

on:
  push:
    branches:
    - capistrano_deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Restore Bundler cache
      id: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-
    - name: Install dependecies
      run: bundle install
    - name: Write deployment key
      run: echo $SSH_KEY > ${{ secrets.LISTED_SSH_KEY_PATH }}
      env:
        SSH_KEY: ${{secrets.LISTED_SSH_KEY}}
    - name: Deploy with Capistrano
      run: bundle exec cap staging deploy
      env:
        LISTED_SSH_KEY_PATH: ${{ secrets.LISTED_SSH_KEY_PATH }}
        LISTED_SSH_USER: ${{ secrets.LISTED_SSH_USER }}
        LISTED_SSH_SERVER: ${{ secrets.LISTED_SSH_SERVER }}
        LISTED_SSH_DEPLOY_TO: ${{ secrets.LISTED_SSH_DEPLOY_TO }}
