name: Deploy with Capistrano

on:
  push:
    branches:
    - capistrano_deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Write deployment key
      run: echo $SSH_KEY > ${{ secrets.LISTED_SSH_KEY_PATH }}
      env:
        SSH_KEY: ${{secrets.LISTED_SSH_KEY}}
    - name: Add public IP to AWS security group
      uses: sohelamin/aws-security-group-add-ip-action@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID_DEV }}
        port: '22'
        description: 'GitHub Action'
    - name: Deploy with Capistrano
      run: bundle exec cap staging deploy
      env:
        LISTED_SSH_KEY_PATH: ${{ secrets.LISTED_SSH_KEY_PATH }}
        LISTED_SSH_USER: ${{ secrets.LISTED_SSH_USER }}
        LISTED_SSH_SERVER: ${{ secrets.LISTED_SSH_SERVER }}
        LISTED_SSH_DEPLOY_TO: ${{ secrets.LISTED_SSH_DEPLOY_TO }}
