name: PR

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs Brakeman vulnerability scanner
        uses: standardnotes/brakeman-action@v1.0.0
        with:
          options: "--color"
